sudo: required
services:
 - docker
 before_install: 
  - docker build -t client/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run client/react-test npm test -- --coverage

# Build prod versions of all project after success
after_success:
  - docker build -t client/multi-client ./client
  - docker build -t nginx/multi-nginx ./nginx
  - docker build -t server/multi-server ./server
  - docker build -t worker/multi-worker ./worker
  # log in to the docker cli to upload image in docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push -t client/multi-client 
  - docker push nginx/multi-nginx 
  - docker push server/multi-server 
  - docker push worker/multi-worker
